name: ci
on: push
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
      uses: actions/checkout@v2
      - name: Set Node.js 17.x
      uses: actions/setup-node@v1
      with:
        node-version: "17.x"
        cache: 'npm'
      - name: Install packages
      run: npm ci
      - name: ESLint
      run: npm run lint
